# Copyright 2020, Battelle Energy Alliance, LLC
# ALL RIGHTS RESERVED
"""
ga.py — Genetic Algorithm for Resource-Constrained Project Scheduling (RCPSP)

Implements the Activity List representation and one-point crossover operator
from Hartmann (1998) / Kolisch & Hartmann (1999), using DEAP as the GA engine.

References
----------
Kolisch, R. and Hartmann, S. (1999). Heuristic Algorithms for Solving the
Resource-Constrained Project Scheduling Problem: Classification and
Computational Analysis. In J. Weglarz (ed.), Project Scheduling: Recent
Models, Algorithms and Applications, 147-178. Kluwer.

Hartmann, S. (1998). A competitive genetic algorithm for resource-constrained
project scheduling. Naval Research Logistics.

Chromosome representation
-------------------------
A **precedence-feasible activity list**

    λ = [i₀, i₁, ..., i_{N-1}]

where each element is the index of an activity in ``pert.forwardDict`` (i.e.
``pert.forwardDict.keys()`` enumerated once at construction time).  Activity
at position g must have all its predecessors at earlier positions (precedence
feasibility).

``pert.priority_calculation()`` with ``reorder_by_dependencies()`` always
produces precedence-feasible orderings, so all chromosomes derived from named
priority rules are valid.  Random chromosomes are generated by calling the
same pipeline with ``priority_rule='random'``.

Decoding (fitness evaluation)
------------------------------
A chromosome is decoded by passing the corresponding ordered list of
``Activity`` objects to ``pert.calculateSerialScheduleWithResources()`` via
the ``_ordered`` keyword added in this release.  Fitness =
``out['scheduled_duration'] - 2`` (strips dummy start/end overhead).

Initial population
------------------
One individual per entry in ``PRIORITY_RULES`` is seeded using
``priority_calculation`` to build the ordering.  The schedule durations from
both serial SGS (``calculateSerialScheduleWithResources``) and parallel SGS
(``calculateScheduleWithResources(sgs='max_use_res_ranked')``) are recorded
for the same priority rule for benchmarking purposes only.  Remaining
population slots are filled with random precedence-feasible permutations.

Crossover — Hartmann (1998) one-point crossover for activity lists
------------------------------------------------------------------
Given mother λᴹ and father λᶠ and a random cut point q (1 ≤ q < N):

1. The first q positions of the child are taken directly from the mother.
2. The remaining N-q positions are filled by scanning the father from left
   to right and appending each activity not yet present in the child.

Hartmann (1998) proves that a child produced this way from two
precedence-feasible parents is itself precedence-feasible.

Two children are produced symmetrically (roles of mother and father swapped).

Mutation
--------
Disabled as per design specification.

Requirements
------------
    pip install deap
"""

from __future__ import annotations

import logging
import random
from typing import Any, Dict, List, Optional, Tuple

import numpy as np

try:
    from deap import algorithms, base, creator, tools
except ImportError as _deap_err:
    raise ImportError(
        "DEAP is required by ga.py. Install it with:  pip install deap"
    ) from _deap_err

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Priority rules used to seed the initial population.
# Must match rules accepted by Pert.priority_calculation().
# ---------------------------------------------------------------------------
PRIORITY_RULES: List[str] = [
    'es', 'ef', 'ls', 'lf', 'duration', 'random',
    'mts', 'mtp', 'grpw', 'grd', 'rr', 'avgrr',
    'maxrr', 'minrr', 'irsm', 'wcs', 'acs',
    'mehh_8000_b', 'mehh_3375_b', 'mehh_1000_b', 'mehh_125_b', 'gphh_b',
]


class RCPSPGeneticAlgorithm:
    """
    Genetic Algorithm optimiser for RCPSP using the Activity List
    representation and the serial SGS decoder (Hartmann 1998).

    Parameters
    ----------
    pert : Pert
        A fully initialised ``Pert`` object.  ``generateInfo()`` must have
        been called so that ``infoDict`` entries are populated.
    pop_size : int
        Total population size.  The first ``min(len(PRIORITY_RULES), pop_size)``
        slots are seeded from named priority rules; the rest are random
        precedence-feasible permutations.
    n_gen : int
        Number of GA generations.
    cxpb : float
        Probability of applying crossover to a selected pair of parents.
    seed : int
        RNG seed for reproducibility.
    hof_size : int
        Number of elite individuals kept in the Hall of Fame across all
        generations.
    verbose : bool
        Print generation statistics and seeding table to stdout.
    """

    # DEAP creator type names (module-level singletons; guarded against
    # re-creation across multiple instantiations in the same process).
    _FITNESS_CLS = "FitnessMinRCPSP"
    _INDIVIDUAL_CLS = "IndividualRCPSP"

    def __init__(
        self,
        pert,
        pop_size: int = 50,
        n_gen: int = 100,
        cxpb: float = 0.8,
        seed: int = 42,
        hof_size: int = 5,
        verbose: bool = True,
    ) -> None:
        self.pert = pert
        self.pop_size = pop_size
        self.n_gen = n_gen
        self.cxpb = cxpb
        self.hof_size = hof_size
        self.verbose = verbose

        random.seed(seed)
        np.random.seed(seed)

        # Fixed enumeration of all activities; order matches forwardDict
        self._activities: List[Any] = list(pert.forwardDict.keys())
        self._n: int = len(self._activities)
        self._act_to_idx: Dict[Any, int] = {
            a: i for i, a in enumerate(self._activities)
        }

        self._setup_deap()

    # ---------------------------------------------------------------------- #
    # DEAP registration                                                        #
    # ---------------------------------------------------------------------- #

    def _setup_deap(self) -> None:
        """Register DEAP fitness / individual types and genetic operators."""
        if not hasattr(creator, self._FITNESS_CLS):
            creator.create(self._FITNESS_CLS, base.Fitness, weights=(-1.0,))
        if not hasattr(creator, self._INDIVIDUAL_CLS):
            creator.create(
                self._INDIVIDUAL_CLS,
                list,
                fitness=getattr(creator, self._FITNESS_CLS),
            )
        self._Ind = getattr(creator, self._INDIVIDUAL_CLS)

        tb = base.Toolbox()
        tb.register("evaluate", self._evaluate)
        tb.register("mate", self._crossover_one_point)
        # Mutation is intentionally omitted.
        tb.register("select", tools.selTournament, tournsize=3)
        self.toolbox = tb

    # ---------------------------------------------------------------------- #
    # Chromosome ↔ activity list conversion                                    #
    # ---------------------------------------------------------------------- #

    def _rule_to_chromosome(self, rule: str) -> List[int]:
        """
        Build a precedence-feasible activity list chromosome from a priority rule.

        Calls ``pert.priority_calculation(all_acts, priority_rule=rule)``.
        ``priority_calculation`` applies ``reorder_by_dependencies`` internally,
        which performs a lexicographic topological sort that guarantees
        precedence feasibility.

        The chromosome is a list of integer indices into ``self._activities``.

        Parameters
        ----------
        rule : str
            Any priority rule accepted by ``Pert.priority_calculation()``.
            Use ``'random'`` to obtain a random precedence-feasible permutation.

        Returns
        -------
        list of int, length ``self._n``
        """
        all_acts = list(self.pert.forwardDict.keys())
        raw = self.pert.priority_calculation(all_acts, priority_rule=rule)

        # priority_calculation returns [(Activity, raw_val, inv_rank), ...] for
        # all rules (including 'random' after normalize_tuples + reorder).
        # Extract the ordered Activity list.
        if raw and isinstance(raw[0], tuple):
            ordered_acts = [a for (a, _, _) in raw]
        else:
            ordered_acts = list(raw)  # fallback (shouldn't occur)

        return [self._act_to_idx[a] for a in ordered_acts]

    def _chromosome_to_activities(self, chromosome: List[int]) -> List[Any]:
        """Convert an index-list chromosome to an ordered list of Activity objects."""
        return [self._activities[i] for i in chromosome]

    # ---------------------------------------------------------------------- #
    # Initial population                                                       #
    # ---------------------------------------------------------------------- #

    def generate_initial_population(self) -> List[Any]:
        """
        Build the initial population.

        For each rule in ``PRIORITY_RULES`` (up to ``pop_size``):

        1. Derive a precedence-feasible activity list chromosome via
           ``_rule_to_chromosome(rule)``.
        2. Record the schedule duration produced by the same priority rule
           under *both* SGS variants for benchmarking:

           - Serial SGS: ``calculateSerialScheduleWithResources(priority_rule=rule)``
           - Parallel SGS: ``calculateScheduleWithResources(sgs='max_use_res_ranked',
             priority_rule=rule)``

        Remaining slots are filled with random precedence-feasible permutations
        obtained by calling ``_rule_to_chromosome('random')``, which applies
        ``priority_calculation`` with ``priority_rule='random'`` and thereby
        uses ``reorder_by_dependencies`` to enforce topological feasibility.

        ``pert.priorities`` is cleared to ``None`` before each named-rule SGS
        call so that any previously injected external priorities do not
        interfere.

        Returns
        -------
        list of IndividualRCPSP
        """
        population: List[Any] = []
        seed_info: Dict[str, Dict[str, float]] = {}

        for rule in PRIORITY_RULES:
            if len(population) >= self.pop_size:
                break
            try:
                # --- chromosome from rule ordering ---
                chromosome = self._rule_to_chromosome(rule)
                population.append(self._Ind(chromosome))

                # --- serial SGS duration (informational) ---
                self.pert.priorities = None
                serial_out = self.pert.calculateSerialScheduleWithResources(
                    priority_rule=rule
                )

                # --- parallel SGS duration (informational) ---
                self.pert.priorities = None
                parallel_out = self.pert.calculateScheduleWithResources(
                    sgs='max_use_res_ranked', priority_rule=rule
                )

                seed_info[rule] = {
                    'serial': serial_out['scheduled_duration'] - 2,
                    'parallel': parallel_out['scheduled_duration'] - 2,
                }

            except Exception as exc:  # noqa: BLE001
                logger.warning(
                    "Skipping rule '%s' during population seeding: %s", rule, exc
                )

        # --- fill remaining slots with random precedence-feasible permutations ---
        n_random = 0
        while len(population) < self.pop_size:
            chromosome = self._rule_to_chromosome('random')
            population.append(self._Ind(chromosome))
            n_random += 1

        if seed_info and self.verbose:
            all_dur = [v for info in seed_info.values() for v in info.values()]
            print(
                f"\nInitial population: {len(seed_info)} rule-seeded + "
                f"{n_random} random  |  best seeded = {min(all_dur):.2f} h\n"
            )
            print(f"  {'Rule':<22} {'Serial (h)':>12} {'Parallel (h)':>14}")
            print("  " + "-" * 50)
            for r, info in seed_info.items():
                print(
                    f"  {r:<22} {info['serial']:>12.2f} {info['parallel']:>14.2f}"
                )
            print()
        elif seed_info:
            all_dur = [v for info in seed_info.values() for v in info.values()]
            logger.info(
                "Initial population: %d rule-seeded + %d random | "
                "best seeded duration = %.2f h",
                len(seed_info),
                n_random,
                min(all_dur),
            )

        return population

    # ---------------------------------------------------------------------- #
    # Fitness evaluation                                                       #
    # ---------------------------------------------------------------------- #

    def _evaluate(self, individual: List[int]) -> Tuple[float, ...]:
        """
        Decode an activity list chromosome and evaluate fitness using the
        Serial SGS.

        The chromosome (index permutation) is converted to an ordered list of
        ``Activity`` objects and passed to
        ``pert.calculateSerialScheduleWithResources(_ordered=...)`` which
        schedules each activity at the earliest feasible time consistent with
        the given ordering, precedence constraints, and resource/equipment/
        location capacity.

        Parameters
        ----------
        individual : list of int
            Precedence-feasible permutation of activity indices.

        Returns
        -------
        tuple of float
            ``(scheduled_duration - 2,)`` — single-objective minimisation.
        """
        ordered_acts = self._chromosome_to_activities(individual)
        out = self.pert.calculateSerialScheduleWithResources(_ordered=ordered_acts)
        return (out['scheduled_duration'] - 2,)

    # ---------------------------------------------------------------------- #
    # Crossover — Hartmann (1998) one-point crossover for activity lists       #
    # ---------------------------------------------------------------------- #

    @staticmethod
    def _crossover_one_point(
        ind1: List[int], ind2: List[int]
    ) -> Tuple[List[int], List[int]]:
        """
        One-point crossover for precedence-feasible activity lists.

        Algorithm (Hartmann 1998, Section 4.2.1):
        ------------------------------------------
        Given mother λᴹ (``ind1``) and father λᶠ (``ind2``):

        1. Draw a random cut point q with 1 ≤ q < N.
        2. Child 1 inherits positions 1..q from the mother.
        3. The remaining positions of Child 1 are filled by scanning the
           father left-to-right and appending each activity not already
           present in the child.
        4. Child 2 is built symmetrically (mother and father roles swapped).

        Hartmann (1998) proves that when both parents are precedence-feasible
        the child produced by this operator is also precedence-feasible,
        because:
        - The prefix is directly taken from a feasible list ⇒ each of those
          activities has all its predecessors before it.
        - The suffix preserves the relative order of the father, which is
          itself feasible, and only activities whose predecessors are already
          covered by the prefix are pulled in from that relative order first.

        Example (paper, p. 11, q = 3):
            λᴹ = [1, 3, 2, 5, 4, 6]
            λᶠ = [2, 4, 6, 1, 3, 5]
            λᶜ = [1, 3, 2, 4, 6, 5]

        Parameters
        ----------
        ind1, ind2 : list of int
            Parent chromosomes.  Modified **in place** per DEAP convention.

        Returns
        -------
        (ind1, ind2) : modified children
        """
        n = len(ind1)
        if n < 2:
            return ind1, ind2

        q = random.randint(1, n - 1)

        # --- Child 1: prefix from ind1 (mother), suffix from ind2 (father) ---
        prefix1 = list(ind1[:q])
        taken1 = set(prefix1)
        suffix1 = [gene for gene in ind2 if gene not in taken1]
        ind1[:] = prefix1 + suffix1

        # --- Child 2: prefix from ind2 (mother), suffix from ind1 (father) ---
        prefix2 = list(ind2[:q])
        taken2 = set(prefix2)
        suffix2 = [gene for gene in ind1 if gene not in taken2]
        ind2[:] = prefix2 + suffix2

        return ind1, ind2

    # ---------------------------------------------------------------------- #
    # Main optimisation loop                                                   #
    # ---------------------------------------------------------------------- #

    def run(self) -> Tuple[tools.HallOfFame, tools.Logbook]:
        """
        Execute the genetic algorithm.

        Workflow
        --------
        1. Generate initial population (priority-rule seeding + random fill).
        2. Evaluate fitness for every individual in generation 0.
        3. For each of ``n_gen`` generations:
           a. Tournament selection.
           b. Pairwise crossover with probability ``cxpb`` (no mutation).
           c. Re-evaluate invalidated offspring.
           d. Generational replacement.
           e. Update Hall of Fame and statistics logbook.

        Returns
        -------
        hof : deap.tools.HallOfFame
            Top ``hof_size`` individuals found across all generations.
        log : deap.tools.Logbook
            Per-generation statistics:
            ``gen``, ``nevals``, ``min``, ``avg``, ``std``, ``max``.
        """
        # ── Generation 0 ─────────────────────────────────────────────────────
        pop = self.generate_initial_population()

        fitnesses = list(map(self.toolbox.evaluate, pop))
        for ind, fit in zip(pop, fitnesses):
            ind.fitness.values = fit

        hof = tools.HallOfFame(self.hof_size)
        stats = tools.Statistics(lambda ind: ind.fitness.values[0])
        stats.register("min", np.min)
        stats.register("avg", np.mean)
        stats.register("std", np.std)
        stats.register("max", np.max)

        log = tools.Logbook()
        log.header = ["gen", "nevals"] + stats.fields
        hof.update(pop)
        record = stats.compile(pop)
        log.record(gen=0, nevals=len(pop), **record)
        if self.verbose:
            print(log.stream)

        # ── Generational loop ─────────────────────────────────────────────────
        for gen in range(1, self.n_gen + 1):
            # Selection
            offspring = list(
                map(self.toolbox.clone, self.toolbox.select(pop, len(pop)))
            )

            # Crossover (mutation disabled)
            for child1, child2 in zip(offspring[::2], offspring[1::2]):
                if random.random() < self.cxpb:
                    self.toolbox.mate(child1, child2)
                    del child1.fitness.values
                    del child2.fitness.values

            # Evaluate invalidated individuals
            invalid = [ind for ind in offspring if not ind.fitness.valid]
            for ind, fit in zip(invalid, map(self.toolbox.evaluate, invalid)):
                ind.fitness.values = fit

            # Generational replacement
            pop[:] = offspring
            hof.update(pop)

            record = stats.compile(pop)
            log.record(gen=gen, nevals=len(invalid), **record)
            if self.verbose:
                print(log.stream)

        logger.info(
            "GA finished | best = %.2f h | generations = %d | pop_size = %d",
            hof[0].fitness.values[0],
            self.n_gen,
            self.pop_size,
        )
        return hof, log

    # ---------------------------------------------------------------------- #
    # Result helpers                                                           #
    # ---------------------------------------------------------------------- #

    def get_best_schedule(self, hof: tools.HallOfFame) -> Dict:
        """
        Decode the best chromosome and return the full schedule result dict.

        Runs ``calculateSerialScheduleWithResources`` with the best activity
        list ordering so the ``Pert`` object is left in the state of the best
        found schedule (Gantt chart, constrained chain, etc. are accessible).

        Parameters
        ----------
        hof : HallOfFame
            As returned by ``run()``.

        Returns
        -------
        dict
            Same keys as ``calculateSerialScheduleWithResources``:
            ``scheduled_duration``, ``cpm_duration``, ``delay_hours``,
            ``n_activities``, ``n_completed``, ``priority_rule``.
        """
        ordered_acts = self._chromosome_to_activities(hof[0])
        return self.pert.calculateSerialScheduleWithResources(_ordered=ordered_acts)

    def get_best_activity_list(self, hof: tools.HallOfFame) -> List[str]:
        """
        Return the best chromosome as a human-readable list of task IDs.

        Parameters
        ----------
        hof : HallOfFame
            As returned by ``run()``.

        Returns
        -------
        list of str
            Activity names in the best scheduling order.
        """
        return [self._activities[i].returnName() for i in hof[0]]

    def get_convergence_summary(self, log: tools.Logbook) -> Dict:
        """
        Extract a concise convergence summary from the logbook.

        Parameters
        ----------
        log : Logbook
            As returned by ``run()``.

        Returns
        -------
        dict with keys:
            ``n_gen``, ``best_duration``, ``initial_best``, ``improvement``,
            ``final_avg``, ``final_std``.
        """
        gen0 = log[0]
        final = log[-1]
        return {
            'n_gen': len(log) - 1,
            'best_duration': final['min'],
            'initial_best': gen0['min'],
            'improvement': gen0['min'] - final['min'],
            'final_avg': final['avg'],
            'final_std': final['std'],
        }
